//Users
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

//Products
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

//Logbook
export const FETCH_LOGBOOKS = 'FETCH_LOGBOOKS';
export const FETCH_LOGBOOK = 'FETCH_LOGBOOK';
export const CREATE_LOGBOOK = 'CREATE_LOGBOOK';
export const UPDATE_LOGBOOK = 'UPDATE_LOGBOOK';
export const DELETE_LOGBOOK = 'DELETE_LOGBOOK';

//Todo
export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODO = 'FETCH_TODO';
export const CREATE_TODO = 'CREATE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_TODO_PROPERTY_VALUE = 'UPDATE_TODO_PROPERTY_VALUE';
